### ISSUE TITLE
GIT Feedback

### ISSUE THREAD

**Issue by sunghj1118** [hajin-kim/ybigta-23th-onboarding#1]
readme.md에 자료를 정리해서 올려주셔서 채점하고 읽기 편했으며, resources 폴더 또한 만들어주셔서 좋았습니다. commit convention을 지켜주신 점과 다 쓰신 branch를 삭제하신 점 또한 인상적이었습니다. 굿 👍 🧇

**Comment by hajin-kim** [comment]
감사합니다 :) 채점하시느라 수고하셨습니다 ㅎㅎ
