### ISSUE TITLE
DB/SQL 채점

### ISSUE THREAD

**Issue by Joirv** [hajin-kim/ybigta-23th-onboarding#2]
![최고예요](https://github.com/hajin-kim/ybigta-23th-onboarding/assets/118533218/5674ad01-2ad2-434d-964d-d28010cdac7a)

과제 너무 열심히 해주셔서 감사합니다!
과제2번 ERD로 제출해주신 점도 인상적이었습니당ㅎㅎ
수고 많으셨습니다:)

**Comment by hajin-kim** [comment]
감사합니다 ㅎㅎ 고생이 많으십니다~
